-- core/icons.lua
-- GENERATED by scripts/rasterize_icons.sh - do not edit by hand.
-- 64x64 RGBA PNGs, rasterized from scripts/icon_*.svg.

local M = {}

local ICONS = {
	["delete"] = "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABmJLR0QA/wD/AP+gvaeTAAACq0lEQVR4nO2au24UMRSGPxKk"
		.. "RIQUKMkjgNJDgUIVGqjoUiUFdNQISl6BnpqSZiWqPAARD0BBRwFUIZBsxGopcil2lqDZY8drH9uzyvkkSzseX47/9e2MDYZh"
		.. "GIZhGPq8BvaBs8Sw35Q1U2yT3vB22M5h6FyOQoHHM1JmNgEWZqTMbALMDNcL1vUJeBOY9gVwP6Mt/ygpwDfgfWDaLQoJcOWH"
		.. "QAhrQA8Yor+05QrDxuY1DQF6HWhQbOhd1rhrAQL8AW4EpOsiA2DJlyBkDviqY0sVVGx/CPSp352nDf3Gdi8hQwBgBXjAxW7s"
		.. "CbDTSvMLeP7f8zyw3vz+ApwE1hWS/y1wq5X+HfCh+f0X+AgcTFlnMM+QZ95SSCvS05iCYvcBkrILwM3I8qZhGdkviPq3YwX4"
		.. "6YhfFeLG+4gB8BnY9JS72aQZ4F7HpTp8NmXhDvLEc1dI295H9JEbscrkZCut4/ccdd+OaYjmEAC5YY9az8vAhpBuo3nny+uq"
		.. "w2eTl1gBfiPP6pJxi8pxUh0nwKEQfymxApwyWvbauP4dTaQ6DhjZNDUp3qDU5VYSygtFqiN6vU8RQJp1awkQvQJoC1BrCFQR"
		.. "QOp2NeeAKGwIJBhiPUCIKyFAp3tAbodI1REC/R4AeXuBuiNkAsRm9FSacyVwlV1FgEPCHSItXI7QUWyBKQLUcIhUHSFIPxor"
		.. "7RCpOkKQLkDp3aDqHgDyCFB6CHReAOlzeWxc5wQI8Qd2W8/HwJ6Qb69558ur6gdo8IrJr7PfW2k0P4v/EOp7mdSCREqfEKmd"
		.. "CI3JMQfkcohcjlDSHJB6R8g1/nY872JxLa/SZqwYrhOikiHqRGhMjiFQmiQbQu8HuJhjdIVGOsEpwZDRFZhqvsApk2t1SXZJ"
		.. "aLwWNa7RqV6DMwzDMAzjanIOPUSQSHhWCscAAAAASUVORK5CYII=",
	["load"] = "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABmJLR0QA/wD/AP+gvaeTAAADsElEQVR4nO3bzYscRRjH8c+6"
		.. "iZcoCAmaNahRcbOKiN6iB4keBIUIgsccJQRcXSLi/6AETBBX1JOKKPEgmqCI8eWiRnMTSWJEDya+BAMRlBx0d9ZD9ZBhrZ7p"
		.. "nq6enp30Fwp2qp56+qlfT9fL07O0tLS0XMJMlbDdiocxi6triaY/KziOA/hzlBfegrfQyYJoupzATK0j7uEu/FrzgMZWhC3G"
		.. "c/Dd8oOaRXhzDAZZuwh5k+BW/IjLIm3fCV/BLttxXZUgKnIS9+O3lE6fEFf8qYjtODwmyeeEFyMX+TbHtunBVxJhXU79pkjd"
		.. "qRJ+n8dXZYMZwN3Y26d9Dp8q+TjkCRCbGzpFneIo3ilhX4Qim7Y5fI77hEdzILFJbq0zi89wbRHjSRSAEiJMggCLOfWFRJgE"
		.. "AeZVEGESBFgRRHglp30Wn+CqWOMkCEAQYY98EeawEGvIWwarshePJvY5aLvdFQF2R9pvjXVKIcAyplfVbc9K3Syv+twVYQ73"
		.. "rmqLfttTPAInE/gYlhORuhWcLeoghQBvJ/DR2LVTCPAsDifwU5bDeK6qkxRzwL/YiUewQ/ET2eW4Kfv7J/xTsN8vwn7/vcIR"
		.. "DsFB/z9uHkzofw+WenwvuTiDp6Bw/E3sA3YLO7felWMaL+HJUQczSgGmsR8vyz/aHshsVi+rtTEqAa7Eu3J2Y6tYwAdytq6p"
		.. "GYUANwsJkp0l+jyAb7Ctloh6qFuAHfgatw3R9xZ8kfmojToFeAwfYWMFHxvxsXDaq4U6BOhOdq8Ka31V1uEFNU2OqQXYgPcV"
		.. "m+zKspD53pDSaWoB9uGhATZ/Ddkm872vVEQDSCnAFHYNsDml//M8b/D7h13K/a6hL6kFWN+n/YiQIzjTx+ZMZnOkj816YypA"
		.. "B4dy2hbxIM4X8HM+s81LdB5S7iVNX1LPAfM41vP5Ah7PylIJP0s9/S701B+TeElMnRM862I6bBO+xLkK/haFU9w9mZ+jEt59"
		.. "6kmKdoSBp+KcsPzVwqSkxYemFaDpAJqmFaDpAJqmFaDpAJomT4CVErbjSCzW2JhyBxXbvdWen0vElPib4D9ixnkCxF543o6n"
		.. "hwyql+idKNBWhCk8I56DjL1IzT1W3iC8rooJdDwrwwZ7hXDai/Eh/h7SL+Emxe5+Bzfi5zLO1sKPpYuW18oMvMuMkKBoOviq"
		.. "5TQ2DyMA3LnGRTiNO4YdfJcZvCH8HKXpARUty3hdgTtfJrd2vfBPU9twTYl+o+R3fC+kzUpNeC0tLS2XJP8B8Bg6y1kJfxwA"
		.. "AAAASUVORK5CYII=",
	["new"] = "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABmJLR0QA/wD/AP+gvaeTAAABEElEQVR4nO3ay23CQABF0UtE"
		.. "ARSQBpIOWLCgopTgGtKG22CRpXfQAAVQAArZOErCRxp+uRbzjjSSNRKeNw95FpYhIiIiIuo0EtceA7P+egFsxSz/bgJ0wK4f"
		.. "XT9XjYafzX+PxgjyZCwKvBTO3Z1VwLF1lSxWAYORAuwAthRgB7ClADuALQXYAWwpwA5gSwF2AFv1BZz7SmwCvAGvF/z2tynw"
		.. "vDe3Bj6uuOcOWALvwOaK+5w05u9rrKGOrs96c/MBbK50zEs3Vf0ZcI6HfARyCEpaDv+51ghS/RmQAuwAthRgB7ClADuALQXY"
		.. "AWwpwA5gSwF2AFsKkNb9LJy7O6uAVeHcwxrMh5L5VDYiIiIiKvUFA0mjXWElDBUAAAAASUVORK5CYII=",
	["save"] = "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABmJLR0QA/wD/AP+gvaeTAAADq0lEQVR4nO3bTYgcRRjG8d+6"
		.. "i+QUXAjqJujGy2QVI3oQo4KYJeJBNArePCcIaiRB8O5NL5qDHmJAVESJBxUDEoLGkwreRJJoiBCj8SuB5BTIsrseuocMs9Uz"
		.. "XTPV27Oz/Yc6TL1Vb731TNfXVA8NDQ0N65iJiLJb8RRauLmSaHqzjJM4iMur2fAWfIylPIi60ynMVNrjDu7DhYo7NLIibDGa"
		.. "nW+nMyoW4aMR6GTlIhRNgltxFjcEbD/LHsE2O3DbMEEMyWnM46+UTl8SVvxAoOwoDJPkc8LbgUZ+Kihbd+eHEmGqIH9TIO/X"
		.. "CL9v4vvYYPrwIPb3sM/hG5HDoUiA0NywVNYpfsCnEeXLUGbTNodvsVM2NPsSmuTWOi2cwOYyhcdRACJEGAcB3inILyXCOAjw"
		.. "oiFEGAcBlmUiHCqwt/A1bgoZx0EAMhGeVyzCHF4OGYqWwWHZj2cT++y33W6LAHsD9jtDlVIIsIjJrrwdeaqaxa7PbRHm8EiX"
		.. "Lfi0pxgCpxP4GJRTgbxl/FPWQQoBPkngo7a2UwjwOo4m8BPLUbwxrJMUc8ACnsQzeFT5E9mk64eui1aO5yL+lO33vygdYQ9S"
		.. "rgKf5akM9+Nz1zcoF/A0fkwYTynq2AdMyU6KnbuzzXleVctyIXUIcC9mA/mzuW1VqUOAjQPaKmFctsID0whQdwB10whQdwB1"
		.. "0whQdwB10whQdwB1s+4FqOLwcRf2yI66x2XvGZQ96nYziefwmOzI/K7sPaHKOWLl7euREvV24mpXveOY7igzH/DdTvMd5abz"
		.. "up32q3kbyeJPPQTewoauvF2yy9JWhJ9WXmdXV/6GvI1kpBRgEtsLbEUdCtFPsO1W/go9MCkFWMS5HvZpfIXdPcrszstM9yhz"
		.. "zuBzygpSD4HX+tinsK+HfZ/+E3O/NqJILcB7shVgIbFfuc89eRvJqGIfcBiP41JCn5dyn4cT+kR1G6ETeECaNfsMHs59JqdI"
		.. "gOWIskWcxUM4Flmvk2Oyn9B/iawXijXUp8JOXQzkbYsMAq7gCdntUSyHZBcuVyLrTQjfBP8X46ToRclXIoPpZC+uFfjtTNeE"
		.. "r7fLMIFXC/y+UFQhxCx+E35CTuYp+Ej1YZNsPN9YYF/Ad/h3AN9wt/C3v4Q78HuMs7XwsnTZ9H5Mx9vM4I8RCH7YdB63DiIA"
		.. "2VXVWhbhPO4ZtPNtZvChbP9dd4fKpkV8oMQ3H/Onqdtlf5rahlsi6q0mf8v2DF+KnPAaGhoa1iX/A+69T21VcOnmAAAAAElF"
		.. "TkSuQmCC",
}

local cache = {}

-- Returns a love.Graphics.Image for the named icon, or nil if unknown.
function M.decode(name)
	local b64 = ICONS[name]
	if not b64 then
		return nil
	end
	if not cache[name] then
		local raw = love.data.decode("string", "base64", b64)
		cache[name] = love.graphics.newImage(love.data.newByteData(raw))
	end
	return cache[name]
end

return M
