#!/bin/sh
# Rasterize the profile-action SVG icons into base64-embedded PNGs.
#
# Reads scripts/icon_*.svg, rasterizes each to a 64x64 RGBA PNG, and writes
# src/core/icons.lua with the PNGs embedded as base64 strings. The generated
# Lua module is self-contained (no external asset files), so it works from
# source, from the .love archive, and from the fused executable.
#
# Requires: rsvg-convert (librsvg), base64 (coreutils).
#
# Usage: ./scripts/rasterize_icons.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SVG_DIR="$SCRIPT_DIR"
OUT_FILE="$PROJECT_DIR/src/core/icons.lua"

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

# Emit one icon as a Lua table entry, wrapping the base64 into concatenated
# string literals so no line exceeds the linter's line-length limit.
emit_icon() {
	name="$1"
	b64="$2"
	wrapped="$(printf '%s' "$b64" | fold -w 96)"
	first="$(printf '%s\n' "$wrapped" | head -n 1)"
	rest="$(printf '%s\n' "$wrapped" | tail -n +2)"
	if [ -z "$rest" ]; then
		printf '\t["%s"] = "%s",\n' "$name" "$first"
		return
	fi
	printf '\t["%s"] = "%s"\n' "$name" "$first"
	printf '%s\n' "$rest" | awk '
		{ lines[n++] = $0 }
		END {
			for (i = 0; i < n; i++) {
				comma = (i == n - 1) ? "," : ""
				printf "\t\t.. \"%s\"%s\n", lines[i], comma
			}
		}'
}

{
	printf '%s\n' \
		"-- core/icons.lua" \
		"-- GENERATED by scripts/rasterize_icons.sh - do not edit by hand." \
		"-- 64x64 RGBA PNGs, rasterized from scripts/icon_*.svg." \
		"" \
		"local M = {}" \
		"" \
		"local ICONS = {"
	for svg in "$SVG_DIR"/icon_*.svg; do
		name="$(basename "$svg" .svg)"
		name="${name#icon_}"
		png="$TMP_DIR/$name.png"
		rsvg-convert -w 64 -h 64 "$svg" -o "$png"
		b64="$(base64 -w0 "$png")"
		emit_icon "$name" "$b64"
	done
	printf '%s\n' \
		"}" \
		"" \
		"local cache = {}" \
		"" \
		"-- Returns a love.Graphics.Image for the named icon, or nil if unknown." \
		"function M.decode(name)" \
		"	local b64 = ICONS[name]" \
		"	if not b64 then" \
		"		return nil" \
		"	end" \
		"	if not cache[name] then" \
		"		local raw = love.data.decode(\"string\", \"base64\", b64)" \
		"		cache[name] = love.graphics.newImage(love.data.newByteData(raw))" \
		"	end" \
		"	return cache[name]" \
		"end" \
		"" \
		"return M"
} > "$OUT_FILE"

echo "Wrote $OUT_FILE"
